name: microlens-aeson
version: '2.3.0'
synopsis: Law-abiding lenses for Aeson, using microlens.
description: Law-abiding lenses for Aeson, using microlens.
category: Numeric
author: Colin Woodbury
maintainer: Colin Woodbury <colingw@gmail.com>
copyright: Copyright (C) 2012 Paul Wilson, (C) 2013 Edward A. Kmett, (C) 2015 Colin Woodbury
license: MIT
homepage: http://github.com/fosskers/microlens-aeson/
git: git://github.com/fosskers/microlens-aeson.git
bug-reports: http://github.com/fosskers/microlens-aeson/issues

extra-source-files:
  - AUTHORS.md
  - README.md
  - CHANGELOG.md
  - microlens-aeson.png
  - lens-aeson.png

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

dependencies:
  - base >=4.8 && <5
  - aeson >=0.7.0.5 && <1.4
  - bytestring
  - deepseq
  - hashable
  - microlens >=0.3 && <0.5
  - text >=0.11.1.10 && <1.3
  - unordered-containers >=0.2.3 && <0.3
  - vector >=0.9 && <0.13

library:
  source-dirs: src
  exposed-modules:
    - Lens.Micro.Aeson
  dependencies:
    - attoparsec >=0.10 && <0.14
    - scientific >=0.3.2 && <0.4

tests:
  microlens-aeson-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -threaded
    dependencies:
      - microlens-aeson
      - tasty >=0.10.1.2
      - tasty-hunit >=0.9.2

benchmarks:
  microlens-aeson-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -O2
    dependencies:
      - microlens-aeson
      - criterion >= 1.2 && < 1.5
      - lens-aeson >= 1.0
      - lens >= 4.15 && < 4.17
