name: microlens-aeson
version: '2.2.0.1'
synopsis: Law-abiding lenses for Aeson, using microlens.
description: Law-abiding lenses for Aeson, using microlens.
category: Numeric
author: Colin Woodbury
maintainer: Colin Woodbury <colingw@gmail.com>
copyright: Copyright (C) 2012 Paul Wilson, (C) 2013 Edward A. Kmett, (C) 2015 Colin Woodbury
license: MIT
homepage: http://github.com/fosskers/microlens-aeson/
git: git://github.com/fosskers/microlens-aeson.git
bug-reports: http://github.com/fosskers/microlens-aeson/issues

extra-source-files:
  - AUTHORS.md
  - README.md
  - CHANGELOG.md
  - microlens-aeson.png
  - lens-aeson.png

dependencies:
  - base >=4.8 && <5
  - aeson >=0.7.0.5 && <1.3
  - text >=0.11.1.10 && <1.3
  - microlens >=0.3 && <0.5
  - bytestring >=0.9 && <0.11
  - unordered-containers >=0.2.3 && <0.3
  - vector >=0.9 && <0.13

library:
  source-dirs: src
  ghc-options:
    - -fwarn-tabs
    - -O2
  exposed-modules:
    - Lens.Micro.Aeson
  dependencies:
    - attoparsec >=0.10 && <0.14
    - scientific >=0.3.2 && <0.4

tests:
  microlens-aeson-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -threaded
    dependencies:
      - tasty >=0.10.1.2
      - tasty-hunit >=0.9.2
      - microlens-aeson
