resolver: lts-18.22

flags:
  these:
    assoc: false
  strict:
    assoc: false

extra-deps:
  - aeson-2.0.3.0
  - attoparsec-0.14.4
  - OneTuple-0.3.1
  - hashable-1.4.0.2
  - semialign-1.2.0.1
  - text-2.0
  - text-short-0.1.5
  - time-compat-1.9.6.1
